on: [push, pull_request, workflow_dispatch]
name: soldat
jobs:
  linux-build-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake git fpc libprotobuf-dev protobuf-compiler libssl-dev libsdl2-dev libopenal-dev libphysfs-dev libfreetype6

      - name: Compile soldat
        run: |
          export BUILD_ID=${GITHUB_SHA::8}
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=./soldat -DCMAKE_BUILD_TYPE=Release
          make
          make install
          cmake .. -DBUILD_CLIENT=0 -DCMAKE_INSTALL_PREFIX=./soldatserver -DCMAKE_BUILD_TYPE=Release
          make install

  appimage:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake git fpc libprotobuf-dev protobuf-compiler libssl-dev libsdl2-dev libopenal-dev libphysfs-dev libfreetype6

      - name: Compile soldat
        run: |
          export BUILD_ID=${GITHUB_SHA::8}
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=./soldat/AppDir -DCMAKE_BUILD_TYPE=Release
          make
          make install
          make clean
          cmake .. -DBUILD_CLIENT=0 -DCMAKE_INSTALL_PREFIX=./soldatserver/AppDir -DCMAKE_BUILD_TYPE=Release
          make install

      - name: Build AppImages
        run: |
          ./.github/workflows/make-appimage.sh build/soldat client
          ./.github/workflows/make-appimage.sh build/soldatserver server

      - name: Upload client AppImage
        uses: actions/upload-artifact@v2
        with:
          name: appimages
          path: build/soldat/*.AppImage

      - name: Upload server AppImage
        uses: actions/upload-artifact@v2
        with:
          name: appimages
          path: build/soldatserver/*.AppImage

  continuous:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [appimage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Chmod and zip AppImages
        run: |
          cd appimages
          chmod u+x *.AppImage
          zip linux-appimage.zip Soldat-*.AppImage
          zip linux-server-only-appimage.zip SoldatServer-*.AppImage
          mv linux-appimage.zip linux-server-only-appimage.zip ..

      - name: Upload release
        uses: softprops/action-gh-release@fe9a9bd3295828558c7a3c004f23f3bf77d155b2
        with:
          tag_name: continuous
          files: |
            linux-appimage.zip
            linux-server-only-appimage.zip
          body: Soldat 1.8 alpha dev build
          name: Soldat 1.8 alpha dev build
